import torch
import torch.nn as nn

class TransformerStructureDecoder(nn.Module):
    def __init__(self, vocab_size, d_model=512, nhead=8, num_layers=6):
        super(TransformerStructureDecoder, self).__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)
        
        # Standard PyTorch Transformer Decoder Layer
        self.decoder_layer = nn.TransformerDecoderLayer(
            d_model=d_model, 
            nhead=nhead,
            batch_first=True
        )
        self.transformer_decoder = nn.TransformerDecoder(
            self.decoder_layer, 
            num_layers=num_layers
        )
        
        # Projection layer mapping back to vocabulary token sizes
        self.fc_out = nn.Linear(d_model, vocab_size)

    def forward(self, tgt, memory, tgt_mask=None):
        # tgt: target sequence token IDs (batch_size, seq_len)
        # memory: features generated by the visual backbone encoder
        tgt_emb = self.embedding(tgt)
        output = self.transformer_decoder(tgt_emb, memory, tgt_mask=tgt_mask)
        return self.fc_out(output)